package br.com.gusoliveira21.catgallery.model.modelResultRetrofit

data class Image(
    val account_id: Int?,
    val account_url: String?,
    val ad_type: Int,
    val ad_url: String,
    val animated: Boolean,
    val bandwidth: Long?,
    val comment_count: Int,
    val datetime: Int,
    val description: String?,
    val downs: Int,
    val edited: String,
    val favorite: Boolean?,
    val favorite_count: Int?,
    val has_sound: Boolean,
    val height: Int,
    val id: String?,
    val in_gallery: Boolean?,
    val in_most_viral: Boolean?,
    val is_ad: Boolean?,
    val link: String,
    val nsfw: Boolean?,
    val points: Int?,
    val score: Int?,
    val section: String?,
    val size: Int,
    val tags: List<Any>,
    val title: String,
    val type: String,
    val ups: Int?,
    val views: Int?,
    val vote: String?,
    val width: Int
)